#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# because of some zookeper dependency which is required by default in hive 3.1.3, falling back to 3.1.2
FROM ubuntu as archive
ARG HADOOP_VERSION=3.2.1
ARG HIVE_VERSION=3.1.2
ARG TEZ_VERSION=0.9.1
ARG RANGER_VERSION=2.4.0

RUN apt-get update && apt-get -y install wget
RUN wget --no-check-certificate https://archive.apache.org/dist/tez/$TEZ_VERSION/apache-tez-$TEZ_VERSION-bin.tar.gz && \
 wget --no-check-certificate https://archive.apache.org/dist/hadoop/core/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz && \
 wget --no-check-certificate https://archive.apache.org/dist/hive/hive-$HIVE_VERSION/apache-hive-$HIVE_VERSION-bin.tar.gz
RUN mv /apache-tez-$TEZ_VERSION-bin.tar.gz /opt && \
 mv hadoop-$HADOOP_VERSION.tar.gz /opt && \
 mv apache-hive-$HIVE_VERSION-bin.tar.gz /opt


FROM archive as env
ARG HADOOP_VERSION=3.2.1
ARG HIVE_VERSION=3.1.2
ARG TEZ_VERSION=0.9.1
ARG RANGER_VERSION=2.4.0

RUN tar -xzvf /opt/hadoop-$HADOOP_VERSION.tar.gz -C /opt/ && \
    rm -rf /opt/hadoop-$HADOOP_VERSION/share/doc/* && \
    tar -xzvf /opt/apache-hive-$HIVE_VERSION-bin.tar.gz -C /opt/ && \
    rm -rf /opt/apache-hive-$HIVE_VERSION-bin/jdbc/* && \
    tar -xzvf /opt/apache-tez-$TEZ_VERSION-bin.tar.gz -C /opt && \
    rm -rf /opt/apache-tez-$TEZ_VERSION-bin/share/*

FROM openjdk:8-jdk-slim AS run
ARG HADOOP_VERSION=3.2.1
ARG HIVE_VERSION=3.1.2
ARG TEZ_VERSION=0.9.1
ARG RANGER_VERSION=2.4.0

COPY --from=env /opt/hadoop-$HADOOP_VERSION /opt/hadoop
COPY --from=env /opt/apache-hive-$HIVE_VERSION-bin /opt/hive
COPY --from=env /opt/apache-tez-$TEZ_VERSION-bin /opt/tez

# Install dependencies
RUN set -ex; \
    apt-get update; \
    apt-get -y install procps; \
    rm -rf /var/lib/apt/lists/*

# Set necessary environment variables.
ENV HADOOP_HOME=/opt/hadoop \
    HIVE_HOME=/opt/hive \
    TEZ_HOME=/opt/tez \
    HIVE_VER=$HIVE_VERSION

ENV PATH=$HIVE_HOME/bin:$HADOOP_HOME/bin:$PATH

COPY entrypoint.sh /
COPY ./hive-site.xml $HIVE_HOME/conf/
RUN chmod +x /entrypoint.sh

WORKDIR /opt/hive
EXPOSE 10000 10002 9083

ENV RANGER_HIVE_PLUGIN_HOME /opt/ranger-hive-plugin
COPY ranger-${RANGER_VERSION}-hive-plugin.tar.gz /opt/ranger-${RANGER_VERSION}-hive-plugin.tar.gz
COPY ./atlas/atlas-hive-hook /opt/atlas-hive-hook
COPY ./atlas/hive-env.sh /opt/hive/conf/hive-env.sh
COPY ./atlas/atlas-application.properties /opt/hive/conf/atlas-application.properties

RUN tar -xvf /opt/ranger-${RANGER_VERSION}-hive-plugin.tar.gz -C /opt/ \
    && ln -s /opt/ranger-${RANGER_VERSION}-hive-plugin $RANGER_HIVE_PLUGIN_HOME \
    && rm -f /opt/ranger-${RANGER_VERSION}-hive-plugin.tar.gz \
    && rm /opt/tez/lib/jersey*.jar

# https://issues.apache.org/jira/browse/HIVE-22915
RUN rm $HIVE_HOME/lib/guava-19.0.jar && \
    cp $HADOOP_HOME/share/hadoop/hdfs/lib/guava-27.0-jre.jar $HIVE_HOME/lib/

ENV HIVE_SITE_CONF_hive_exec_post_hooks=org.apache.atlas.hive.hook.HiveHook
ENV HIVE_SITE_CONF_atlas_hook_hive_maxthreads=5
ENV HIVE_SITE_CONF_hive_server2_async_exec_threads=100

COPY run.sh /run.sh

ENTRYPOINT ["/run.sh"]
