version: "2"
services:

  atlas-server:
    build: ../../dockerfiles/atlas
    image: vijayjangir/apache-atlas:2.3.0
    restart: always
    container_name: atlas-server
    volumes:
      - ./mnt/data:/opt/atlas/data
      - ./ranger/install.properties:/opt/atlas/ranger-atlas-plugin/install.properties
      # - ./atlas/mnt:/mnt
    environment:
      MANAGE_LOCAL_HBASE: true
      MANAGE_LOCAL_SOLR: true
      JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk

    ports:
      - "21000:21000"
    depends_on:
      - "zookeeper"
      - "kafka" 

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    restart: always
    hostname: zookeeper
    ports:
      - "2181:2181"  

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "create_events:1:1,delete_events:1:1,ATLAS_HOOK:1:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper  
  
  

networks:
  default:
    external:
      name: ranger-env
