version: '3.7'

services:

  postgres-db:
    image: postgres:9.6
    volumes:
      - psql_data:/var/lib/psql/data
    restart: always
    # command: --default-authentication-plugin=mysql_native_password
    container_name: ranger-psqldb
    environment:
      POSTGRES_USER: ranger
      POSTGRES_PASSWORD: ranger
      POSTGRES_DB: ranger
      PGDATA: /var/lib/psql/data/pgdata
      MYSQL_DATABASE: ranger
      MYSQL_USER: ranger
      MYSQL_PASSWORD: ranger
    expose:
      - "5432"
    ports:
      - "5432:5432"

  image_build_step:
    build: 
      context: /Users/b0228188/projects/darts2/apache-ranger/target/ # path to the ranger tar files
      dockerfile: /Users/b0228188/projects/github_repos/apache-ranger-docker-poc/dockerfiles/ranger/base/Dockerfile # path to dockerfile
      args:
        RANGER_VERSION: 2.4.0
    image: vijayjangir/ranger-base:2.4.0

  ranger-admin:
    build: ../../dockerfiles/ranger/admin
    image: vijayjangir/ranger-admin:2.4.0
    container_name: ranger-admin
    hostname: ranger
    depends_on:
      - postgres-db
      - image_build_step
    volumes:
      - ./admin/bootstrap.sh:/opt/ranger_admin/bootstrap.sh
      - ./admin/install.properties:/opt/ranger_admin/install.properties
    command: ["./bootstrap.sh"]
    ports:
      - "6080:6080"
      - "5001:5005"
    restart: always
  # ranger-usersync:
  #   build: ../../dockerfiles/ranger/usersync
  #   image: vijayjangir/ranger-usersync:2.4.0
  #   container_name: ranger-usersync
  #   hostname: usersync
  #   depends_on:
  #     - ranger-admin
  #   volumes:
  #     - ./usersync/bootstrap.sh:/opt/ranger_usersync/bootstrap.sh
  #     - ./usersync/install.properties:/opt/ranger_usersync/install.properties
  #   command: ["./bootstrap.sh"]
  #   restart: always
  #  ranger-usersync-ldap:
  #    image: kadensungbincho/ranger-usersync:2.1.0
  #    container_name: ranger2.0.0-usersync-ldap
  #    hostname: usersync-ldap
  #    depends_on:
  #      - ranger-admin
  #    volumes:
  #      - ./usersync/bootstrap-ldap.sh:/opt/ranger_usersync/bootstrap.sh
  #      - ./usersync/install-ldap.properties:/opt/ranger_usersync/install-hdfs.properties
  #      - ./usersync/templates:/templates
  #      - ./usersync/conf.dist/log4j.properties:/opt/ranger_usersync/conf.dist/log4j.properties
  #    command: ["./bootstrap.sh"]

  ranger-tagsync:
    build: ../../dockerfiles/ranger/tagsync
    image: vijayjangir/ranger-tagsync:2.4.0
    container_name: ranger-tagsync
    hostname: tagsync
    ports:
      - "5005:5005"
    depends_on:
      - ranger-admin
    volumes:
      - ./tagsync/bootstrap.sh:/opt/ranger_tagsync/bootstrap.sh
      - ./tagsync/install.properties:/opt/ranger_tagsync/install.properties
      - ./tagsync/logback.xml:/opt/ranger_tagsync/conf.dist/logback.xml
    command: ["./bootstrap.sh"]
    restart: always

volumes:
  psql_data:
    driver: local

networks:
  default:
    name: ranger-env
