version: '3.7'

services:

  # db:
  #   image: mysql:5.7
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: always
  #   # command: --default-authentication-plugin=mysql_native_password
  #   container_name: ranger-db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: ranger
  #     MYSQL_USER: ranger
  #     MYSQL_PASSWORD: ranger
  #   expose:
  #     - "3306"
  postgres-db:
    image: postgres:9.6
    volumes:
      - psql_data:/var/lib/psql/data
    restart: always
    # command: --default-authentication-plugin=mysql_native_password
    container_name: ranger-psqldb
    environment:
      POSTGRES_USER: ranger
      POSTGRES_PASSWORD: ranger
      POSTGRES_DB: ranger
      PGDATA: /var/lib/psql/data/pgdata
      MYSQL_DATABASE: ranger
      MYSQL_USER: ranger
      MYSQL_PASSWORD: ranger
    expose:
      - "5432"
  ranger-admin:
    image: ranger-admin:2.4.0
    container_name: ranger-admin
    hostname: ranger
    depends_on:
      - postgres-db
    volumes:
      - ./admin/bootstrap.sh:/opt/ranger_admin/bootstrap.sh
      - ./admin/install.properties:/opt/ranger_admin/install.properties
    command: ["./bootstrap.sh"]
    ports:
      - "6080:6080"
    restart: always
  ranger-usersync:
    image: ranger-usersync:2.4.0
    container_name: ranger-usersync
    hostname: usersync
    depends_on:
      - ranger-admin
    volumes:
      - ./usersync/bootstrap.sh:/opt/ranger_usersync/bootstrap.sh
      - ./usersync/install.properties:/opt/ranger_usersync/install.properties
    command: ["./bootstrap.sh"]
    restart: always
  #  ranger-usersync-ldap:
  #    image: kadensungbincho/ranger-usersync:2.1.0
  #    container_name: ranger2.0.0-usersync-ldap
  #    hostname: usersync-ldap
  #    depends_on:
  #      - ranger-admin
  #    volumes:
  #      - ./usersync/bootstrap-ldap.sh:/opt/ranger_usersync/bootstrap.sh
  #      - ./usersync/install-ldap.properties:/opt/ranger_usersync/install-hdfs.properties
  #      - ./usersync/templates:/templates
  #      - ./usersync/conf.dist/log4j.properties:/opt/ranger_usersync/conf.dist/log4j.properties
  #    command: ["./bootstrap.sh"]
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: ranger-es
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - xpack.security.http.ssl.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false

    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    mem_limit: "1024M"


volumes:
  db_data:
    driver: local
  es_data:
    driver: local
  psql_data:
    driver: local

networks:
  default:
    external:
      name: ranger-env
