version: '3.7'

services:

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: ranger-es
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - xpack.security.http.ssl.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - ELASTIC_PASSWORD=Elasticsearch@123
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    mem_limit: "1024M"

volumes:
  es_data:
    driver: local

networks:
  default:
    external:
      name: ranger-env
